"use client";
import { useEffect,useState } from "react";
type Item={id:string;name:string;value:number;active:boolean}; type Tier={id:string;minQuantity:number;factor:number;active:boolean}; type QuoteRow={id:string;status:string;createdAt:string;publicToken:string|null};
type Catalog={products:Item[];materials:Item[];finishes:Item[];dies:Item[];quantityTiers:Tier[]};
const empty:Catalog={products:[],materials:[],finishes:[],dies:[],quantityTiers:[]};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function AdminPage(){
 const[catalog,setCatalog]=useState<Catalog>(empty),[quotes,setQuotes]=useState<QuoteRow[]>([]),[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[key,setKey]=useState(""),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 const load=()=>{setLoading(true);fetch("/api/admin/catalog").then(async r=>{const d=await r.json();if(r.status===401){setAuth(false);return}if(!r.ok)throw new Error(d.error);setCatalog(d.catalog);setAuth(true)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load();fetch("/api/quotes?limit=50").then(r=>r.ok?r.json():null).then(d=>d&&setQuotes(d.quotes||[])).catch(()=>{})},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setError("");const r=await fetch("/api/admin/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({key})});const d=await r.json();if(!r.ok){setError(d.error);return}setKey("");load()};
 const save=async()=>{setError("");setSaved(false);const r=await fetch("/api/admin/catalog",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(catalog)});const d=await r.json();if(!r.ok){setError(d.error);return}setCatalog(d.catalog);setSaved(true);setTimeout(()=>setSaved(false),2500)};
 const updateItem=(group:keyof Omit<Catalog,"quantityTiers">,id:string,patch:Partial<Item>)=>setCatalog(c=>({...c,[group]:c[group].map(i=>i.id===id?{...i,...patch}:i)}));
 const updateTier=(id:string,patch:Partial<Tier>)=>setCatalog(c=>({...c,quantityTiers:c.quantityTiers.map(i=>i.id===id?{...i,...patch}:i)}));
 const table=(title:string,group:keyof Omit<Catalog,"quantityTiers">,unit:string)=><section className="section"><header><h2>{title}</h2><span>{catalog[group].length} itens</span></header><div className="rows"><div className="row head"><span>Nome</span><span>Preço</span><span>Status</span></div>{catalog[group].map(i=><div className="row" key={i.id}><div><input value={i.name} onChange={e=>updateItem(group,i.id,{name:e.target.value})}/><small>{i.id}</small></div><label>R$ <input className="num" type="number" min="0" step="0.01" value={i.value} onChange={e=>updateItem(group,i.id,{value:Number(e.target.value)})}/>{unit&&<small> / {unit}</small>}</label><label className="switch"><input type="checkbox" checked={i.active} onChange={e=>updateItem(group,i.id,{active:e.target.checked})}/>{i.active?"Ativo":"Inativo"}</label></div>)}</div></section>;
 if(loading)return <main className="page"><p>Carregando…</p></main>;
 if(!auth)return <main className="login"><div className="card"><div className="brand">COLAE<span>.</span></div><p className="eyebrow">BACKOFFICE</p><h1>Acesso administrativo</h1><p>Informe a chave configurada no ambiente da aplicação.</p><form onSubmit={login}><input autoFocus type="password" placeholder="Chave administrativa" value={key} onChange={e=>setKey(e.target.value)}/><button>Entrar</button></form>{error&&<div className="error">{error}</div>}</div></main>;
 return <main className="page"><header className="top"><a href="/" className="brand">COLAE<span>.</span></a><button className="ghost" onClick={async()=>{await fetch("/api/admin/auth",{method:"DELETE"});setAuth(false)}}>Sair</button></header><section className="hero"><p className="eyebrow">CENTRAL DE OPERAÇÕES</p><h1>Catálogo e<br/><em>regras de preço.</em></h1><p>Edite os parâmetros que alimentam o motor de orçamento da COLAE.</p></section>{error&&<div className="error">{error}</div>}{saved&&<div className="success">Catálogo salvo. Os próximos orçamentos usarão os novos valores.</div>}{table("Produtos","products","unidade")}{table("Materiais","materials","m²")}{table("Acabamentos","finishes","m²")}{table("Facas","dies","unidade")}<section className="section"><header><h2>Faixas de quantidade</h2><span>{catalog.quantityTiers.length} regras</span></header><div className="rows">{catalog.quantityTiers.map(t=><div className="row" key={t.id}><div><strong>{t.id}</strong><small>Mínimo de unidades</small></div><label><input className="num" type="number" min="1" value={t.minQuantity} onChange={e=>updateTier(t.id,{minQuantity:Number(e.target.value)})}/></label><label>fator <input className="num" type="number" min="0" step="0.01" value={t.factor} onChange={e=>updateTier(t.id,{factor:Number(e.target.value)})}/><input type="checkbox" checked={t.active} onChange={e=>updateTier(t.id,{active:e.target.checked})}/> ativo</label></div>)}</div></section><section className="section"><header><h2>Orçamentos recentes</h2><span>últimos 50</span></header><div className="quoteList">{quotes.map(q=><div className="q" key={q.id}><div><strong>#{q.id.slice(0,8)}</strong><small>{new Date(q.createdAt).toLocaleString("pt-BR")}</small></div><span className={"status "+q.status}>{q.status}</span><a href={q.publicToken?"/orcamento/"+q.id+"?token="+encodeURIComponent(q.publicToken):"/orcamento/"+q.id}>Abrir</a></div>)}</div></section><div className="actions"><button onClick={save}>Salvar catálogo</button>{saved&&<span>✓ salvo</span>}</div><style>{`
:root{--navy:#0F1D3A;--mint:#29C2B1}.page{max-width:1180px;margin:auto;padding:28px 24px 80px}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:29px;font-weight:900;letter-spacing:-2px;color:var(--navy);text-decoration:none}.brand span{color:var(--mint)}.hero{padding:65px 0 35px}.hero h1{font-size:clamp(42px,6vw,76px);line-height:.95;letter-spacing:-.06em;margin:8px 0 24px}.hero em{color:var(--mint);font-style:normal}.hero p:last-child{max-width:650px;font-size:18px;color:#596173}.eyebrow{font-size:10px;font-weight:800;letter-spacing:.16em;color:#747b8c}.section{background:#fff;border:1px solid #e1e3e9;border-radius:20px;margin:18px 0;overflow:hidden}.section header{display:flex;justify-content:space-between;padding:20px 22px;border-bottom:1px solid #e8e9ee}.section h2{font-size:20px;margin:0}.section header span{font-size:11px;color:#737989}.row{display:grid;grid-template-columns:1.5fr 1fr .7fr;gap:18px;padding:14px 22px;border-bottom:1px solid #f0f1f4;align-items:center}.row:last-child{border:0}.head{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:#737989}.row input:not([type=checkbox]){border:1px solid #dfe2e8;border-radius:9px;padding:9px 10px;font:inherit;width:100%;box-sizing:border-box}.row .num{max-width:130px}.row small{display:block;color:#8b91a0;font-size:10px;margin-top:4px}.switch{font-size:12px}.login{min-height:100vh;display:grid;place-items:center;padding:24px;background:#f5f6f8}.card{width:min(420px,100%);background:#fff;padding:34px;border-radius:24px;box-shadow:0 20px 60px #0f1d3a14}.card h1{font-size:32px;letter-spacing:-.04em}.card form{display:grid;gap:12px}.card input{padding:13px;border:1px solid #dfe2e8;border-radius:10px;font:inherit}.actions{position:sticky;bottom:20px;display:flex;gap:12px;align-items:center;justify-content:flex-end;margin-top:25px}.actions button,.card button{background:var(--navy);color:#fff;border:0;border-radius:999px;padding:13px 20px;font-weight:800;cursor:pointer}.ghost{border:1px solid #ddd;background:#fff;border-radius:999px;padding:9px 14px;cursor:pointer}.quoteList{padding:4px 0}.q{display:grid;grid-template-columns:1fr auto auto;gap:18px;align-items:center;padding:14px 22px;border-bottom:1px solid #f0f1f4}.q small{display:block;color:#8b91a0;margin-top:4px}.q a{color:#0F1D3A;font-weight:800;text-decoration:none}.status{font-size:10px;font-weight:800;text-transform:uppercase;border-radius:999px;padding:7px 10px;background:#eef0f4}.status.approved{background:#e5faf6;color:#12786c}.status.rejected{background:#fff0ee;color:#b42318}.success,.error{padding:14px 16px;border-radius:14px;margin:15px 0}.success{background:#e5faf6;color:#12786c}.error{background:#fff0ee;color:#b42318}@media(max-width:700px){.row{grid-template-columns:1fr}.actions{justify-content:stretch}.actions button{width:100%}}
`}</style></main>;
}