"use client";
import {useEffect,useState} from "react";
type Q={id:string;status:string;input:Record<string,any>;quote:{breakdown?:{total?:number};assumptions?:string[]};createdAt:string};
export default function PublicQuote({params}:{params:Promise<{id:string}>}){const[data,setData]=useState<Q|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{params.then(({id})=>{const token=new URLSearchParams(location.search).get("token");const url=token?"/api/quotes/"+id+"?token="+encodeURIComponent(token):"/api/quotes/"+id;fetch(url).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message))})},[params]);
 const decide=async(status:"approved"|"rejected")=>{const id=data?.id,token=new URLSearchParams(location.search).get("token");if(!id||!token)return;setBusy(true);const r=await fetch("/api/quotes/"+id+"/decision",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,status})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);return}setData(x=>x?{...x,status}:x)};
 if(error)return <main className="page"><div className="card result"><h1>Orçamento indisponível</h1><p>{error}</p></div></main>;
 if(!data)return <main className="page"><div className="card result"><p>Carregando orçamento…</p></div></main>;
 const total=Number(data.quote.breakdown?.total??0),canDecide=!!new URLSearchParams(location.search).get("token")&&(data.status==="draft"||data.status==="sent");
 return <main className="page"><header className="header"><div className="brand">COLAE<span>.</span></div><div className="badge">ORÇAMENTO</div></header><section className="hero"><p className="eyebrow">ORÇAMENTO COLAE</p><h1>Seu projeto.<br/><em>Do jeito certo.</em></h1><p className="lead">Orçamento #{data.id.slice(0,8)} · {new Date(data.createdAt).toLocaleDateString("pt-BR")}</p></section><div className="card result"><div className="topline"><span>STATUS</span><strong>{data.status}</strong></div><span>TOTAL ESTIMADO</span><div className="price">R$ {total.toLocaleString("pt-BR",{minimumFractionDigits:2})}</div><p>Dimensão: {String(data.input.widthMm)} × {String(data.input.heightMm)} mm · Quantidade: {String(data.input.quantity)}</p>{data.quote.assumptions?.map((x,i)=><p key={i}>• {x}</p>)}{canDecide&&<div className="actions"><button disabled={busy} onClick={()=>decide("approved")}>Aprovar orçamento</button><button disabled={busy} className="secondary" onClick={()=>decide("rejected")}>Recusar</button></div>}<p className="note">Este valor é uma estimativa sujeita à confirmação comercial.</p></div><style>{`.page{min-height:100vh;background:#f6f7f9;padding:30px 24px 80px}.header,.page>*{max-width:900px;margin-left:auto;margin-right:auto}.header{display:flex;justify-content:space-between;align-items:center}.brand{font-size:29px;font-weight:900;letter-spacing:-2px;color:#0F1D3A}.brand span{color:#29C2B1}.badge{font-size:10px;font-weight:800;letter-spacing:.14em}.hero{padding:70px 0 35px}.eyebrow{font-size:10px;font-weight:800;letter-spacing:.16em;color:#777}.hero h1{font-size:clamp(44px,7vw,82px);line-height:.92;letter-spacing:-.06em;margin:8px 0 18px}.hero em{color:#29C2B1;font-style:normal}.lead{color:#596173}.card{background:#fff;border:1px solid #e1e3e9;border-radius:24px;padding:28px}.topline{display:flex;justify-content:space-between;margin-bottom:30px;font-size:11px}.price{font-size:clamp(42px,7vw,72px);font-weight:900;letter-spacing:-.05em;color:#0F1D3A;margin:8px 0 18px}.actions{display:flex;gap:12px;margin-top:28px}.actions button{border:0;border-radius:12px;padding:14px 20px;background:#29C2B1;color:#0F1D3A;font-weight:900;cursor:pointer}.actions .secondary{background:#eef0f4}.note{color:#747b8c;font-size:13px;margin-top:25px}`}</style></main>}