"use client";
import { useState } from "react";
export default function Home(){
 const [productId,setProductId]=useState("label"),[materialId,setMaterialId]=useState("bopp-white"),[widthMm,setWidthMm]=useState(50),[heightMm,setHeightMm]=useState(30),[quantity,setQuantity]=useState(1000),[finishId,setFinishId]=useState("none"),[dieId,setDieId]=useState("standard"),[total,setTotal]=useState<number|null>(null),[quoteId,setQuoteId]=useState<string|null>(null),[publicToken,setPublicToken]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const pdfHref = total === null ? "#" : `/api/quote/pdf?productId=${productId}&materialId=${materialId}&widthMm=${widthMm}&heightMm=${heightMm}&quantity=${quantity}&finishId=${finishId}&dieId=${dieId}`;
 const whatsappText = total === null ? "" : `Olá, gostaria de solicitar este orçamento COLAE. Total estimado: R$ ${total.toLocaleString("pt-BR",{minimumFractionDigits:2})}. Configuração: ${widthMm}x${heightMm}mm, ${quantity} unidades.`;
 const whatsappHref = total === null ? "#" : `https://wa.me/?text=${encodeURIComponent(whatsappText)}`;
 async function calculate(){setLoading(true);setError("");setQuoteId(null);try{const r=await fetch("/api/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId,materialId,widthMm,heightMm,quantity,finishIds:[finishId],dieId})});const data=await r.json();if(!r.ok)throw new Error(data.error);setTotal(data.breakdown.total);const saved=await fetch("/api/quotes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:{productId,materialId,widthMm,heightMm,quantity,finishIds:[finishId],dieId},quote:data})});if(saved.ok){const savedData=await saved.json();setQuoteId(savedData.id);setPublicToken(savedData.publicToken??null)}}catch(e){setError(e instanceof Error?e.message:"Não foi possível calcular.");}finally{setLoading(false)}}
 return <main className="page"><header className="header"><div className="brand">COLAE<span>.</span></div><div className="badge">MVP • orçamento instantâneo</div></header><section className="hero"><p className="eyebrow">SUA MARCA COMEÇA NOS DETALHES</p><h1>Crie suas etiquetas.<br/><em>Veja o preço na hora.</em></h1><p className="lead">Configure material, tamanho, quantidade, acabamento e faca. O cálculo é processado no servidor.</p></section><section className="grid"><div className="card form"><label>Produto<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="label">Etiqueta adesiva</option><option value="sticker">Sticker personalizado</option></select></label><label>Material<select value={materialId} onChange={e=>setMaterialId(e.target.value)}><option value="bopp-white">BOPP branco</option><option value="paper-white">Papel branco</option><option value="paper-kraft">Papel kraft</option></select></label><div className="dimensions"><label>Largura (mm)<input type="number" value={widthMm} onChange={e=>setWidthMm(Number(e.target.value))}/></label><label>Altura (mm)<input type="number" value={heightMm} onChange={e=>setHeightMm(Number(e.target.value))}/></label></div><label>Quantidade<input type="number" min="100" step="100" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Acabamento<select value={finishId} onChange={e=>setFinishId(e.target.value)}><option value="none">Sem acabamento</option><option value="matte">Laminação fosca</option><option value="gloss">Laminação brilho</option></select></label><label>Faca<select value={dieId} onChange={e=>setDieId(e.target.value)}><option value="standard">Faca padrão</option><option value="custom">Faca especial</option></select></label>{error&&<p className="error">{error}</p>}<button className="calculate" onClick={calculate} disabled={loading}>{loading?"Calculando...":"Calcular meu orçamento →"}</button></div><aside className="card result"><span>ESTIMATIVA</span>{total===null?<div className="empty"><div className="orb">C</div><h2>Seu orçamento<br/>aparece aqui.</h2><p>Preencha as opções para descobrir uma estimativa.</p></div>:<><p className="result-label">Total estimado</p><div className="price">R$ {total.toLocaleString("pt-BR",{minimumFractionDigits:2})}</div><div className="actions"><a className="secondary" href={pdfHref} target="_blank" rel="noreferrer">Baixar PDF</a><a className="whatsapp" href={whatsappHref} target="_blank" rel="noreferrer">Enviar no WhatsApp</a></div>{quoteId&&<p className="share">Orçamento salvo: <a href={`/orcamento/${quoteId}${publicToken?`?token=${publicToken}`:""}`}>#{quoteId.slice(0,8)}</a></p>}</>}</aside></section></main>
}
