import postgres from "postgres";
import { randomUUID } from "node:crypto";
export type QuoteStatus="draft"|"sent"|"approved"|"rejected"|"expired";
export type StoredQuote={id:string;customerId:string|null;publicToken:string|null;status:QuoteStatus;input:Record<string,unknown>;quote:Record<string,unknown>;createdAt:string;updatedAt:string};
export type Customer={id:string;name:string;email:string|null;phone:string|null;company:string|null;createdAt:string};
function client(){const url=process.env.DATABASE_URL;return url?postgres(url,{max:5,idle_timeout:20,connect_timeout:5}):null;}
export async function saveQuote(id:string,input:Record<string,unknown>,quote:Record<string,unknown>,customer?:Partial<Customer>){const sql=client();if(!sql)return {persisted:false,publicToken:null};try{let customerId:string|null=null;if(customer?.name){const email=typeof customer.email==="string"&&customer.email.trim()?customer.email.trim().toLowerCase():null;const phone=typeof customer.phone==="string"&&customer.phone.trim()?customer.phone.trim():null;const existing=await sql`select id from customers where (${email} is not null and lower(email)=${email}) or (${phone} is not null and phone=${phone}) order by created_at asc limit 1`;customerId=existing[0]?.id??randomUUID();await sql`insert into customers (id,name,email,phone,company) values (${customerId},${customer.name},${email},${phone},${customer.company??null}) on conflict (id) do update set name=excluded.name,email=coalesce(excluded.email,customers.email),phone=coalesce(excluded.phone,customers.phone),company=coalesce(excluded.company,customers.company)`;}const publicToken=randomUUID()+randomUUID();await sql`insert into quotes (id,customer_id,status,public_token,input,quote) values (${id},${customerId},${"draft"},${publicToken},${sql.json(JSON.stringify(input))},${sql.json(JSON.stringify(quote))})`;return {persisted:true,publicToken};}finally{await sql.end();}}
export async function getQuote(id:string):Promise<StoredQuote|null>{const sql=client();if(!sql)return null;try{const rows=await sql`select id,customer_id as "customerId",public_token as "publicToken",status,input,quote,created_at as "createdAt",updated_at as "updatedAt" from quotes where id=${id} limit 1`;return rows[0]?(rows[0] as unknown as StoredQuote):null;}finally{await sql.end();}}
export async function getQuoteForPublic(id:string,token:string):Promise<StoredQuote|null>{const sql=client();if(!sql)return null;try{const rows=await sql`select id,customer_id as "customerId",public_token as "publicToken",status,input,quote,created_at as "createdAt",updated_at as "updatedAt" from quotes where id=${id} and public_token=${token} limit 1`;return rows[0]?(rows[0] as unknown as StoredQuote):null;}finally{await sql.end();}}
export async function listQuotes(limit=50):Promise<StoredQuote[]>{const sql=client();if(!sql)return [];try{const rows=await sql`select id,customer_id as "customerId",public_token as "publicToken",status,input,quote,created_at as "createdAt",updated_at as "updatedAt" from quotes order by created_at desc limit ${Math.min(Math.max(limit,1),100)}`;return rows as unknown as StoredQuote[];}finally{await sql.end();}}
export async function updateQuoteStatus(id:string,status:QuoteStatus){const sql=client();if(!sql)return false;try{const rows=await sql`update quotes set status=${status},updated_at=now() where id=${id}`;return rows.count>0;}finally{await sql.end();}}
export async function updatePublicQuoteStatus(id:string,token:string,status:"approved"|"rejected"){const sql=client();if(!sql)return false;try{const rows=await sql`update quotes set status=${status},updated_at=now() where id=${id} and public_token=${token} and status in (${"draft"},${"sent"})`;return rows.count>0;}finally{await sql.end();}}
export async function getCustomer(id:string):Promise<Customer|null>{const sql=client();if(!sql)return null;try{const rows=await sql`select id,name,email,phone,company,created_at as "createdAt" from customers where id=${id} limit 1`;return rows[0]?(rows[0] as unknown as Customer):null;}finally{await sql.end();}}
export function databaseConfigured(){return Boolean(process.env.DATABASE_URL);}
