"use client";
import {useEffect,useState} from "react";
type Q={id:string;status:string;customerId:string|null;input:Record<string,any>;quote:Record<string,any>;createdAt:string;publicToken:string|null};
const statuses=["draft","sent","approved","rejected","expired"];
export default function QuotesAdmin(){const[quotes,setQuotes]=useState<Q[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>fetch("/api/quotes?limit=100").then(async r=>{if(!r.ok)throw new Error("Não foi possível carregar.");return r.json()}).then(d=>setQuotes(d.quotes||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 const change=async(id:string,status:string)=>{const r=await fetch("/api/quotes/"+id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(!r.ok){const d=await r.json();setError(d.error);return}setQuotes(q=>q.map(x=>x.id===id?{...x,status}:x));};
 return <main className="page"><header><a href="/admin" className="brand">COLAE<span>.</span></a><a href="/admin" className="back">← Dashboard</a></header><section className="hero"><p className="eyebrow">GESTÃO COMERCIAL</p><h1>Orçamentos<br/><em>da COLAE.</em></h1><p>Consulte, acompanhe e atualize o estágio de cada oportunidade.</p></section>{error&&<div className="error">{error}</div>}{loading?<p>Carregando…</p>:<div className="table">{quotes.map(q=><article className="item" key={q.id}><div><strong>#{q.id.slice(0,8)}</strong><small>{new Date(q.createdAt).toLocaleString("pt-BR")}</small><small>{q.input.widthMm} × {q.input.heightMm} mm · {q.input.quantity} un.</small></div><div><span className={"pill "+q.status}>{q.status}</span><select value={q.status} onChange={e=>change(q.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><a href={q.publicToken?"/orcamento/"+q.id+"?token="+encodeURIComponent(q.publicToken):"/orcamento/"+q.id}>Ver orçamento →</a></article>)}</div>}<style>{`
.page{max-width:1100px;margin:auto;padding:30px 24px 80px}.page header{display:flex;justify-content:space-between;align-items:center}.brand{font-size:29px;font-weight:900;letter-spacing:-2px;color:#0F1D3A;text-decoration:none}.brand span{color:#29C2B1}.back{color:#0F1D3A;text-decoration:none;font-weight:700}.hero{padding:70px 0 35px}.eyebrow{font-size:10px;font-weight:800;letter-spacing:.16em;color:#777}.hero h1{font-size:clamp(44px,7vw,78px);line-height:.92;letter-spacing:-.06em;margin:8px 0 20px}.hero em{color:#29C2B1;font-style:normal}.hero p:last-child{color:#596173;font-size:18px}.item{display:grid;grid-template-columns:1.5fr 1fr auto;gap:20px;align-items:center;padding:20px;border:1px solid #e1e3e9;border-radius:18px;margin:10px 0;background:#fff}.item small{display:block;color:#7b8190;margin-top:5px}.item select{margin-left:10px;padding:8px;border:1px solid #ddd;border-radius:8px}.pill{display:inline-block;padding:7px 10px;border-radius:999px;background:#eef0f4;font-size:10px;font-weight:800;text-transform:uppercase}.pill.approved{background:#e5faf6;color:#12786c}.pill.rejected{background:#fff0ee;color:#b42318}.item>a{font-weight:800;color:#0F1D3A;text-decoration:none}.error{padding:14px;background:#fff0ee;color:#b42318;border-radius:12px}@media(max-width:700px){.item{grid-template-columns:1fr}.item select{margin:10px 0 0}}`
}</style></main>;}
